In [1]:
import sqlite3 as sql
import pandas as pd

In [7]:
#connection to database
conn = sql.connect('database.sqlite')
conn

#type of table
pd.read_sql_query("select * from sqlite_master", conn) # query, db connection
 
#tabel
pd.read_sql_query("select * from sqlite_master where type = 'table'", conn)

,type,name,tbl_name,rootpage,sql
0,table,Salaries,Salaries,2,CREATE TABLE Salaries (\n Id INTEGER PRIMAR...

In [9]:
pd.read_sql_query("PRAGMA table_info(salaries)", conn)

    cid              name     type  notnull dflt_value  pk
0     0                Id  INTEGER        0       None   1
1     1      EmployeeName     TEXT        0       None   0
2     2          JobTitle     TEXT        0       None   0
3     3           BasePay  NUMERIC        0       None   0
4     4       OvertimePay  NUMERIC        0       None   0
5     5          OtherPay  NUMERIC        0       None   0
6     6          Benefits  NUMERIC        0       None   0
7     7          TotalPay  NUMERIC        0       None   0
8     8  TotalPayBenefits  NUMERIC        0       None   0
9     9              Year  INTEGER        0       None   0
10   10             Notes     TEXT        0       None   0
11   11            Agency     TEXT        0       None   0
12   12            Status     TEXT        0       None   0

In [10]:
pd.read_sql_query("select * from salaries", conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [11]:
pd.read_sql_query("Select * from salaries where employeename is not null", conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [12]:
pd.read_sql_query("select * from salaries where employeename is  null", conn)

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

In [13]:
pd.read_sql_query("select * from salaries where employeename not  null", conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [19]:
pd.read_sql_query("select distinct jobtitle from salaries", conn)
pd.read_sql_query('select jobtitle, EmployeeName, basepay from salaries', conn)

,JobTitle,EmployeeName,BasePay
0,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,NATHANIEL FORD,167411.18
1,CAPTAIN III (POLICE DEPARTMENT),GARY JIMENEZ,155966.02
2,CAPTAIN III (POLICE DEPARTMENT),ALBERT PARDINI,212739.13
3,WIRE ROPE CABLE MAINTENANCE MECHANIC,CHRISTOPHER CHONG,77916
4,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",PATRICK GARDNER,134401.6
...,...,...,...
148649,Custodian,Roy I Tillery,0
148650,Not provided,Not provided,Not Provided
148651,Not provided,Not provided,Not Provided
148652,Not provided,Not provided,Not Provided
148653,"Counselor, Log Cabin Ranch",Joe Lopez,0

In [22]:
pd.read_sql_query("select employeename as 'Name of Employees' from Salaries",conn)

        Name of Employees
0          NATHANIEL FORD
1            GARY JIMENEZ
2          ALBERT PARDINI
3       CHRISTOPHER CHONG
4         PATRICK GARDNER
...                   ...
148649      Roy I Tillery
148650       Not provided
148651       Not provided
148652       Not provided
148653          Joe Lopez

[148654 rows x 1 columns]

In [27]:
def sql_query(q):
    return pd.read_sql_query(q, conn)

In [ ]:
q = "select basepay, totalpay, otherpay from salaries order by 2 desc"
sql_query(q)

In [ ]:
q = """
select avg(TotalPay) as 'average TP of Custodian'
from Salaries
where JobTitle = 'Custodian'
"""
sql_query(q)