In [84]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [85]:
df = pd.read_csv("titanic_dataset.csv")

In [86]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [88]:
def impute_age(cols):
    age =  cols[0]
    pclass = cols[1]

    if pd.isnull(Age):
        if pclass == 1:
            return 37
        elif pclass == 27:
            return 29
    else:
        return age
    df['age']=df[['age','pclass']].apply(impute_age, axis =1)

In [89]:
df.drop('Cabin', axis = 1, inplace = True)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [91]:
df.dropna(inplace = True)

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Name         712 non-null    object
 4   Sex          712 non-null    object
 5   Age          712 non-null    float64
 6   SibSp        712 non-null    int64
 7   Parch        712 non-null    int64
 8   Ticket       712 non-null    object
 9   Fare         712 non-null    float64
 10  Embarked     712 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 66.8+ KB

In [93]:
df.drop(['Name','Ticket','PassengerId'], axis = 1, inplace = True)

In [94]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [95]:
cat_col = ['Sex', 'Embarked']

for colname in cat_col:
    df[colname] = df[colname].astype('category')

In [96]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  712 non-null    int64
 1   Pclass    712 non-null    int64
 2   Sex       712 non-null    category
 3   Age       712 non-null    float64
 4   SibSp     712 non-null    int64
 5   Parch     712 non-null    int64
 6   Fare      712 non-null    float64
 7   Embarked  712 non-null    category
dtypes: category(2), float64(2), int64(4)
memory usage: 40.6 KB

In [98]:
df.shape

(712, 8)

In [99]:
df.select_dtypes(['category']).columns

Index(['Sex', 'Embarked'], dtype='object')

In [100]:
sex = pd.get_dummies(df['Sex'], drop_first = True)
embarked = pd.get_dummies(df['Embarked'], drop_first = True)

In [101]:
sex

      male
0     True
1    False
2    False
3    False
4     True
..     ...
885  False
886   True
887  False
889   True
890   True

[712 rows x 1 columns]

In [102]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [103]:
df = pd.concat([df, sex, embarked], axis =1)
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,male,Q,S
0,0,3,male,22.0,1,0,7.2500,S,True,False,True
1,1,1,female,38.0,1,0,71.2833,C,False,False,False
2,1,3,female,26.0,0,0,7.9250,S,False,False,True
3,1,1,female,35.0,1,0,53.1000,S,False,False,True
4,0,3,male,35.0,0,0,8.0500,S,True,False,True

In [104]:
df = df.drop(['Sex', 'Embarked'], axis = 1)

In [105]:
df.head()

   Survived  Pclass   Age  SibSp  Parch     Fare   male      Q      S
0         0       3  22.0      1      0   7.2500   True  False   True
1         1       1  38.0      1      0  71.2833  False  False  False
2         1       3  26.0      0      0   7.9250  False  False   True
3         1       1  35.0      1      0  53.1000  False  False   True
4         0       3  35.0      0      0   8.0500   True  False   True

In [106]:
df.shape

(712, 9)

In [107]:
 x = df.drop('Survived', axis = 1)
 y = df['Survived']

In [108]:
x

     Pclass   Age  SibSp  Parch     Fare   male      Q      S
0         3  22.0      1      0   7.2500   True  False   True
1         1  38.0      1      0  71.2833  False  False  False
2         3  26.0      0      0   7.9250  False  False   True
3         1  35.0      1      0  53.1000  False  False   True
4         3  35.0      0      0   8.0500   True  False   True
..      ...   ...    ...    ...      ...    ...    ...    ...
885       3  39.0      0      5  29.1250  False   True  False
886       2  27.0      0      0  13.0000   True  False   True
887       1  19.0      0      0  30.0000  False  False   True
889       1  26.0      0      0  30.0000   True  False  False
890       3  32.0      0      0   7.7500   True   True  False

[712 rows x 8 columns]

In [109]:
from sklearn import preprocessing
pre_process = preprocessing.StandardScaler().fit(x)
x_transform = pre_process.fit_transform(x)

In [110]:
x_transform

array([[ 0.90859974, -0.52766856,  0.52251079, ...,  0.75613751,
        -0.20232566,  0.53403984],
       [-1.48298257,  0.57709388,  0.52251079, ..., -1.32251077,
        -0.20232566, -1.87251946],
       [ 0.90859974, -0.25147795, -0.55271372, ..., -1.32251077,
        -0.20232566,  0.53403984],
       ...,
       [-1.48298257, -0.73481151, -0.55271372, ..., -1.32251077,
        -0.20232566,  0.53403984],
       [-1.48298257, -0.25147795, -0.55271372, ...,  0.75613751,
        -0.20232566, -1.87251946],
       [ 0.90859974,  0.16280796, -0.55271372, ...,  0.75613751,
         4.94252683, -1.87251946]])

In [111]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = .20, random_state = 101)

In [112]:
x_train.shape
x_train

     Pclass   Age  SibSp  Parch      Fare   male      Q      S
66        2  29.0      0      0   10.5000  False  False   True
813       3   6.0      4      2   31.2750  False  False   True
830       3  15.0      1      0   14.4542  False  False  False
741       1  36.0      1      0   78.8500   True  False   True
581       1  39.0      1      1  110.8833  False  False  False
..      ...   ...    ...    ...       ...    ...    ...    ...
98        2  34.0      0      1   23.0000  False  False   True
753       3  23.0      0      0    7.8958   True  False   True
724       1  27.0      1      0   53.1000   True  False   True
422       3  29.0      0      0    7.8750   True  False   True
663       3  36.0      0      0    7.4958   True  False   True

[569 rows x 8 columns]

In [113]:
x_train.shape
x_train = x_train.dropna()

In [114]:
y_train.shape

(569,)

In [115]:
from sklearn.linear_model import LogisticRegression
print('Logistic Regression')
log_reg = LogisticRegression()

log_reg.fit(x_train, y_train)

Logistic Regression

LogisticRegression()

In [116]:
from sklearn.metrics import accuracy_score
y_pred_log_reg = log_reg.predict(x_test)

print('logistic')
log_reg_accuracy = round(accuracy_score(y_test, y_pred_log_reg) * 100, 2)
print('accuracy', log_reg_accuracy)

logistic
accuracy 81.12

In [120]:
comparison_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_log_reg})

comparison_df

     Actual  Predicted
225       0          0
449       1          0
750       1          1
261       1          0
283       1          0
..      ...        ...
230       1          1
371       0          0
700       1          1
833       0          0
539       1          1

[143 rows x 2 columns]